spring:
  application:
    name: backend
  config:
    import: "optional:configtree:/run/secrets/"
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    username: ${MYSQL_USERNAME}
    password: ${mysql_root_password}
  jpa:
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
jwt:
  secret-key: ${jwt_secret_key}
  issuer: ticketflow
  audience: ticketflow-client
  expiration-minutes: 15
  refresh-token-expiry-days: 7
server:
  port: 8080